### ISSUE TITLE
Build failure for docker with Mac M1

### ISSUE THREAD

**Issue by xzwDavid** [assist-project/so-many-fuzzers-artifact#1]
Hi~ guys,

I am running on Mac M1.
I met this problem when I run the ${WORKPATH}/src/suites-management/run-ground-truth-campaign.sh -b uip-overflow -f symcc -n 2 -t 10m --output ${WORKPATH}/test/uip-overflow".

The gcc-mulitilib seems not supported the arm64?

<img width="929" alt="Screen Shot 2023-04-15 at 18 14 02" src="https://user-images.githubusercontent.com/96334838/232207792-26ffa6e0-b7c7-4da8-b165-a93909e1e77a.png">

**Comment by kostis** [comment]
Thanks for your interest in our paper, its artifact, and this repository!

I am not fortunate to have a Mac, let alone an M1-based one, but my two co-authors (@cponcelets, @nvt) have Macs and perhaps they can help.

However, a Google search quickly reveals that this is a known (recent?) issue as e.g. you can see [here](https://groups.google.com/g/linux.debian.bugs.dist/c/K1Eyuc8qtWs) (and in some other places on the web).

May I suggest that you first try our artifact on some Linux-based machine?

**Comment by xzwDavid** [comment]
Hi~
Thanks for your reply.
I am glad to hear that some of you guys work on mac m1 .

I think the primary problem caused by arm64 Architecture.
I fix the first issue by changing the gcc-multilib with "g++-multilib-arm-linux-gnueabi" .

While this problem is solved, I encountered a make error :
<img width="870" alt="Screen Shot 2023-04-15 at 21 45 08" src="https://user-images.githubusercontent.com/96334838/232227866-08e42ad2-bb35-4557-ab81-3ec11294cd70.png">

Happened in this command.

<img width="779" alt="Screen Shot 2023-04-15 at 21 51 01" src="https://user-images.githubusercontent.com/96334838/232228344-a3ad9579-82d0-4895-ab32-674c0a815ae7.png">

**Comment by cponcelets** [comment]
I indeed tried the scripts on a MAC.
Unfortunately, my MAC is too old to have this problem and I cannot reproduce it.

It looks like the issue is when compiling the instrumented target using afl-clang. 
Maybe you can try afl-clang beside and see if you can fix instrumenting a target with it.
